version: "3.4"
services:
  jenkinsmaster:
   image: my_jenkins
   volumes:
     - jenkins_home:/var/jenkins_home
     - jenkins_log:/var/log/jenkins
   ports:
    - "50000:50000"
  jenkinsnginx:
   image: my_nginx
   ports:
    - "80:80"
networks:
  default:
    external:
      name: jenkins
volumes:
  jenkins_home:
  jenkins_log:
